### ISSUE TITLE
Would you be open to additional code commenting?

### ISSUE THREAD

**Issue by ThermalSpan** [swiftcoder/isosurface#5]
I have been using this repo as a guide while learning about marching cubes / oct tree duals / Morton codes. I appreciate the elegance in your implementation, in particular the use of closures to promote code reuse.  I have also been reading through the paper you linked, as well as some of their sources, as I'm not sure I could have connected everything on my own. 

As I learn, I have been adding comments to the code to help me solidify my understanding. Given that this the only rust library of its kind (that I can find) I thought it might be useful to others to have these notes (particularly if they don't have access to the academic articles in question.) Would you be open to a pull request adding my additional code comments? I would of course be willing to edit them to your satisfaction. I understand either way!

**Comment by swiftcoder** [comment]
For some reason I never saw this notification. Certainly open to comments and refactors - this code is not always as clear as it could be.

**Comment by swiftcoder** [comment]
Post the 0.1 refactor, the core algorithm implementations should be significantly clearer to read. Feel free to open a new issue for any specific clarifications.
